version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jira
      - SPRING_DATASOURCE_USERNAME=jira
      - SPRING_DATASOURCE_PASSWORD=JiraRush
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=jira
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=JiraRush
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: